[package]
name = "acc2tax"
version = "0.1.0"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "acc2tax"
crate-type = ["cdylib", "rlib"]

[dependencies]
flate2 = "1.0.11"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.4"
twox-hash = "1.5.0"
itertools = "0.8.0"
crossbeam = "0.7.2"
once_cell = "1.2.0"
bytelines = "2.2.2"
mimalloc = { version = "*", default-features = false }
snap = "0.2.5"
rayon = "1.2.0"
indicatif = "0.12.0"
thincollections = "0.5.3"

[dependencies.pyo3]
version = "0.9.0-alpha.1"
features = ["extension-module"]

[profile.dev]
# opt-level = 3

[profile.release]
opt-level = 3
lto = true
# debug = true # Uncomment when needing valgrind
